### ISSUE TITLE
Why is it a js file extension and not ts file extension

### ISSUE THREAD

**Issue by Norfeldt** [theogainey/deno-xbar#3]
It's more a question than an issue. But why is the example(s) using js extension and not ts extension? It's a deno project after all.

**Comment by theogainey** [comment]
Hi @Norfeldt, I included an example that is written in JavaScript along with an example that uses TypeScript to make it clear that it will work with both JavaScript(`.js`) and TypeScript(`.ts`). Even though TypeScript rocks and it's a common Deno convention to use it instead of JavaScript, both will work.  The JavaScript example does likely need updating because the API it's getting data from appears to no longer be online.
